spring:
  application:
    name: logback-demo

logging:
  file:
    #name: ${spring.application.name}
    path: ${user.dir}/logs/${spring.application.name}.log
  level:
    root: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 31
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"