spring:
  application:
    name: logback-demo
  profiles:
    active: prod
logging:
  # 使用文件配置日志：
  # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-log-configuration
  config: classpath:logback-spring.xml

# spring boot yml 配置日志
#logging:
#  file:
#    # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-logging-file-output
#    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
#  level:
#    root: "debug"
#    web: "info"
#    sql: "error"
#  logback:
#    rollingpolicy:
#      max-file-size: 10GB
#      max-history: 31