spring:
  redis:
    host: 192.168.15.161
    port: 6379
    password:
    lettuce: #springboot默认使用lettuce作为redis客户端
      #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
      shutdown-timeout: 100
      pool:
        # 连接池最大连接数（负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值代表没有限制），单位ms
        max-wait: -1
  cache:
    redis:
      #是否缓存空值，默认为true
      cache-null-values: false