--- # server config
server:
  port: 8081

--- # dubbo config
dubbo:
  scan:
    base-packages: org.msdemt.simple.dubbo_zk_registry_demo_provider.dubbo.service.impl
  protocol:
    name: dubbo
    port: -1
  registry: #单注册中心
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
#  registries: #多注册中心
#    - zk1:
#      id:zk1
#      timeout: 5000
#      address: zookeeper//192.168.15.161:2181
#      default: true
#    - zk2:
#      id: zk2
#      timeout: 5000
#      address: zookeeper//192.168.15.5:2181

--- # project config
user:
  service:
    version: 1.0.0

--- #log config
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 31
      total-size-cap: 0B  #默认0B，保留所有日志
  level:
    root: "debug"
    web: info
    sql: info

