spring:
  application:
    name: dubbo-nacos-registry-provider
server:
  port: 8081
# Dubbo Application
## The default value of dubbo.application.name is ${spring.application.name}
## dubbo.application.name=${spring.application.name}

dubbo:
  scan:
    # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
    base-packages: org.msdemt.simple.dubbo_nacos_registry_provider
  protocol:
    # Dubbo Protocol
    name: dubbo
    ## Random port
    port: -1
  registry:
    ## Dubbo Registry address
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}

## DemoService version
user:
  service:
    version: 1.0.0

nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
